name: Flutter CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-channel: [ "stable", "beta" ]
    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: ${{ matrix.flutter-channel }}

    - name: Cache Pub dependencies
      uses: actions/cache@v3
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pub-

    - name: Install dependencies
      run: flutter pub get

    - name: Run analyzer
      run: flutter analyze --no-fatal-infos

    - name: Run tests
      run: flutter test --coverage

    - name: Build APK
      run: flutter build apk --release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
