name: Flutter CI Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'  # You can change to any version you use
          channel: 'stable'

      # Cache dependencies for faster builds
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run static analysis
      - name: Analyze code
        run: flutter analyze

      # Run tests (optional - you can remove if no tests exist)
      - name: Run tests
        run: flutter test --no-pub --coverage

      # Build release APK
      - name: Build release APK
        run: flutter build apk --release

      # Upload built artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk