name: Build Flutter APK

on:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Fix old dependencies and SDK for null safety
        run: |
          # Fix environment SDK to enable null safety
          sed -i 's/sdk: .*/sdk: ">=2.12.0 <4.0.0"/' pubspec.yaml || \
          echo -e "environment:\n  sdk: \">=2.12.0 <4.0.0\"" >> pubspec.yaml
          
          # Force update outdated packages to null-safe versions
          sed -i 's/cupertino_icons: .*/cupertino_icons: ^1.0.8/' pubspec.yaml || true
          sed -i 's/google_fonts: .*/google_fonts: ^6.3.0/' pubspec.yaml || true
          sed -i 's/flutter_svg: .*/flutter_svg: ^2.0.10+1/' pubspec.yaml || true
          
          # Upgrade dependencies
          flutter pub upgrade --major-versions

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release --ignore-deprecation

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk